package cn.nukkit.network.protocol;

/**
 * author: MagicDroidX & iNevet
 * Nukkit Project
 */
public interface Info {

    byte CURRENT_PROTOCOL = 34;

    byte LOGIN_PACKET = -113;
    byte PLAY_STATUS_PACKET = -112;
    byte DISCONNECT_PACKET = -111;
    byte BATCH_PACKET = -110;
    byte TEXT_PACKET = -109;
    byte SET_TIME_PACKET = -108;
    byte START_GAME_PACKET = -107;
    byte ADD_PLAYER_PACKET = -106;
    byte REMOVE_PLAYER_PACKET = -105;
    byte ADD_ENTITY_PACKET = -104;
    byte REMOVE_ENTITY_PACKET = -103;
    byte ADD_ITEM_ENTITY_PACKET = -102;
    byte TAKE_ITEM_ENTITY_PACKET = -101;
    byte MOVE_ENTITY_PACKET = -100;
    byte MOVE_PLAYER_PACKET = -99;
    byte REMOVE_BLOCK_PACKET = -98;
    byte UPDATE_BLOCK_PACKET = -97;
    byte ADD_PAINTING_PACKET = -96;
    byte EXPLODE_PACKET = -95;
    byte LEVEL_EVENT_PACKET = -94;
    byte TILE_EVENT_PACKET = -93;
    byte ENTITY_EVENT_PACKET = -92;
    byte MOB_EFFECT_PACKET = -91;
    byte UPDATE_ATTRIBUTES_PACKET = -90;
    byte MOB_EQUIPMENT_PACKET = -89;
    byte MOB_ARMOR_EQUIPMENT_PACKET = -88;
    byte INTERACT_PACKET = -87;
    byte USE_ITEM_PACKET = -86;
    byte PLAYER_ACTION_PACKET = -85;
    byte HURT_ARMOR_PACKET = -84;
    byte SET_ENTITY_DATA_PACKET = -83;
    byte SET_ENTITY_MOTION_PACKET = -82;
    byte SET_ENTITY_LINK_PACKET = -81;
    byte SET_HEALTH_PACKET = -80;
    byte SET_SPAWN_POSITION_PACKET = -79;
    byte ANIMATE_PACKET = -78;
    byte RESPAWN_PACKET = -77;
    byte DROP_ITEM_PACKET = -76;
    byte CONTAINER_OPEN_PACKET = -75;
    byte CONTAINER_CLOSE_PACKET = -74;
    byte CONTAINER_SET_SLOT_PACKET = -73;
    byte CONTAINER_SET_DATA_PACKET = -72;
    byte CONTAINER_SET_CONTENT_PACKET = -71;
    byte CRAFTING_DATA_PACKET = -70;
    byte CRAFTING_EVENT_PACKET = -69;
    byte ADVENTURE_SETTINGS_PACKET = -68;
    byte TILE_ENTITY_DATA_PACKET = -67;
    //byte PLAYER_INPUT_PACKET = -66;
    byte FULL_CHUNK_DATA_PACKET = -65;
    byte SET_DIFFICULTY_PACKET = -64;
    //byte CHANGE_DIMENSION_PACKET = -63;
    //byte SET_PLAYER_GAMETYPE_PACKET = -62;
    byte PLAYER_LIST_PACKET = -61;

}
