package cn.nukkit.network.protocol;

/**
 * author: MagicDroidX & iNevet
 * Nukkit Project
 */
public interface ProtocolInfo {

    /**
     * Actual Minecraft: PE protocol version
     */
    byte CURRENT_PROTOCOL = 100;
    String MINECRAFT_VERSION = "v1.0.0";
    String MINECRAFT_VERSION_NETWORK = "1.0.0";

    byte LOGIN_PACKET = 0x01;//1
    byte PLAY_STATUS_PACKET = 0x02;//2
    byte SERVER_TO_CLIENT_HANDSHAKE_PACKET = 0x03;//3
    byte CLIENT_TO_SERVER_HANDSHAKE_PACKET = 0x04;//4
    byte DISCONNECT_PACKET = 0x05;//5
    byte BATCH_PACKET = 0x06;//6
    byte RESOURCE_PACKS_INFO_PACKET = 0x07;//7
    byte RESOURCE_PACK_STACK_PACKET = 0x08;//8
    byte RESOURCE_PACK_CLIENT_RESPONSE_PACKET = 0x09;//9
    byte TEXT_PACKET = 0x0a;//10
    byte SET_TIME_PACKET = 0x0b;//11
    byte START_GAME_PACKET = 0x0c;//12
    byte ADD_PLAYER_PACKET = 0x0d;//13
    byte ADD_ENTITY_PACKET = 0x0e;//14
    byte REMOVE_ENTITY_PACKET = 0x0f;//15
    byte ADD_ITEM_ENTITY_PACKET = 0x10;//16
    byte ADD_HANGING_ENTITY_PACKET = 0x11;//17
    byte TAKE_ITEM_ENTITY_PACKET = 0x12;//18
    byte MOVE_ENTITY_PACKET = 0x13;//19
    byte MOVE_PLAYER_PACKET = 0x14;//20
    byte RIDER_JUMP_PACKET = 0x15;//21
    byte REMOVE_BLOCK_PACKET = 0x16;//22
    byte UPDATE_BLOCK_PACKET = 0x17;//23
    byte ADD_PAINTING_PACKET = 0x18;//24
    byte EXPLODE_PACKET = 0x19;//25
    byte LEVEL_SOUND_EVENT_PACKET = 0x1a;//26
    byte LEVEL_EVENT_PACKET = 0x1b;//27
    byte BLOCK_EVENT_PACKET = 0x1c;//28
    byte ENTITY_EVENT_PACKET = 0x1d;//29
    byte MOB_EFFECT_PACKET = 0x1e;//30
    byte UPDATE_ATTRIBUTES_PACKET = 0x1f;//31
    byte MOB_EQUIPMENT_PACKET = 0x20;//32
    byte MOB_ARMOR_EQUIPMENT_PACKET = 0x21;//33
    byte INTERACT_PACKET = 0x22;//34
    byte USE_ITEM_PACKET = 0x23;//35
    byte PLAYER_ACTION_PACKET = 0x24;//36
    byte PLAYER_FALL_PACKET = 0x25;//37
    byte HURT_ARMOR_PACKET = 0x26;//38
    byte SET_ENTITY_DATA_PACKET = 0x27;//39
    byte SET_ENTITY_MOTION_PACKET = 0x28;//40
    byte SET_ENTITY_LINK_PACKET = 0x29;//41
    byte SET_HEALTH_PACKET = 0x2a;//42
    byte SET_SPAWN_POSITION_PACKET = 0x2b;//43
    byte ANIMATE_PACKET = 0x2c;//44
    byte RESPAWN_PACKET = 0x2d;//45
    byte DROP_ITEM_PACKET = 0x2e;//46
    byte INVENTORY_ACTION_PACKET = 0x2f;//47
    byte CONTAINER_OPEN_PACKET = 0x30;//48
    byte CONTAINER_CLOSE_PACKET = 0x31;//49
    byte CONTAINER_SET_SLOT_PACKET = 0x32;//50
    byte CONTAINER_SET_DATA_PACKET = 0x33;//51
    byte CONTAINER_SET_CONTENT_PACKET = 0x34;//52
    byte CRAFTING_DATA_PACKET = 0x35;//53
    byte CRAFTING_EVENT_PACKET = 0x36;//54
    byte ADVENTURE_SETTINGS_PACKET = 0x37;//55
    byte BLOCK_ENTITY_DATA_PACKET = 0x38;//56
    byte PLAYER_INPUT_PACKET = 0x39;//57
    byte FULL_CHUNK_DATA_PACKET = 0x3a;//58
    byte SET_COMMANDS_ENABLED_PACKET = 0x3b;//59
    byte SET_DIFFICULTY_PACKET = 0x3c;//60
    byte CHANGE_DIMENSION_PACKET = 0x3d;//61
    byte SET_PLAYER_GAME_TYPE_PACKET = 0x3e;//62
    byte PLAYER_LIST_PACKET = 0x3f;//63
    byte EVENT_PACKET = 0x40;//64
    byte SPAWN_EXPERIENCE_ORB_PACKET = 0x41;//65
    byte CLIENTBOUND_MAP_ITEM_DATA_PACKET = 0x42;//66
    byte MAP_INFO_REQUEST_PACKET = 0x43;//67
    byte REQUEST_CHUNK_RADIUS_PACKET = 0x44;//68
    byte CHUNK_RADIUS_UPDATED_PACKET = 0x45;//69
    byte ITEM_FRAME_DROP_ITEM_PACKET = 0x46;//70
    byte REPLACE_ITEM_IN_SLOT_PACKET = 0x47; //ReplaceSelectedItemPacket//71
    byte GAME_RULES_CHANGED_PACKET = 0x48;//72
    byte CAMERA_PACKET = 0x49;//73
    byte ADD_ITEM_PACKET = 0x4a;//74
    byte BOSS_EVENT_PACKET = 0x4b;//75
    byte SHOW_CREDITS_PACKET = 0x4c;//76
    byte AVAILABLE_COMMANDS_PACKET = 0x4d;//77
    byte COMMAND_STEP_PACKET = 0x4e;//78
    byte RESOURCE_PACK_DATA_INFO_PACKET = 0x4f;//79
    byte RESOURCE_PACK_CHUNK_DATA_PACKET = 0x50;//80
    byte RESOURCE_PACK_CHUNK_REQUEST_PACKET = 0x51;//81
}